apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform
resources:
  - ../../base
  - vpa.yaml
images:
  - name: REGION-docker.pkg.dev/PROJECT_ID/platform-containers/api
    newName: africa-south1-docker.pkg.dev/learning-gke-498507/platform-containers/api
    newTag: latest
